main:
  - name: "/about"
    weight: 100
    identifier: "about"
    url: "/about"
  - name: "/now"
    weight: 100
    identifier: "now"
    url: "/now"
  - name: "/pets"
    weight: 140
    identifier: "pets"
    url: "/pets"
#  - name: "/uses"
#    weight: 150
#    identifier: "uses"
#    url: "/uses"
#  - name: "/home-it"
#    weight: 160
#    identifier: "home-it"
#    url: "/home-it"
  - name: "/notes"
    weight: 200
    identifier: "notes"
    url: "/notes/"
  
    
footer:
  - name: "/privacy"
    weight: 200
    identifier: "privacy"
    url: "/privacy"
  - name: "/colophon"
    weight: 300
    identifier: "colophon"
    url: "/colophon/"
  - name: "/changelog"
    weight: 400
    identifier: "changelog"
    url: "/changelog/"

#sub:
#  - name: "Recommended Readings"
#    weight: 100
#    identifier: "readings"
#    url: "/readings/"

#footer:
#  - name: "imprint"
#    weight: 1
#    identifier: "imprint"
#    url: "/imprint/"
