main:
  - name: "/about"
    weight: 100
    identifier: "about"
    url: "/about"
  - name: "/now"
    weight: 100
    identifier: "now"
    url: "/now"
  - name: "/work"
    weight: 120
    identifier: "work"
    url: "/work"
  - name: "/life"
    weight: 130
    identifier: "life"
    url: "/life"
  - name: "/pets"
    weight: 140
    identifier: "pets"
    url: "/pets"
  - name: "/uses"
    weight: 150
    identifier: "uses"
    url: "/uses"
  - name: "/notes"
    weight: 200
    identifier: "notes"
    url: "/notes/"
  - name: "/colophon"
    weight: 300
    identifier: "colophon"
    url: "/colophon/"
  - name: "/changelog"
    weight: 400
    identifier: "changelog"
    url: "/changelog/"

#sub:
#  - name: "Recommended Readings"
#    weight: 100
#    identifier: "readings"
#    url: "/readings/"

#footer:
#  - name: "imprint"
#    weight: 1
#    identifier: "imprint"
#    url: "/imprint/"