main:
  - name: "About"
    weight: 100
    identifier: "about"
    url: "/"
  - name: "Milestones"
    weight: 200
    identifier: "milestones"
    url: "/milestones/"
  - name: "Skills"
    weight: 300
    identifier: "skills"
    url: "/skills/"

#footer:
#  - name: "imprint"
#    weight: 1
#    identifier: "imprint"
#    url: "/imprint/"