
title: "Christian Gehlen"
author: "Christian Gehlen"
copyright: "2023"
description: "Product Manager and Software-Developer for Telcos"
avatar: "images/profile.jpg" 
menu_item_separator: "|"

homepage: 
  - "about"

singleDateFormat: "2006-02-01"
indexDateFormat: "2006-02-01"
listDateFormat: "2006-02-01"


social:
  "Linkedin":
    icon: "linkedin"
    title: "Linkedin"
    url: "https://www.linkedin.com/in/christian-gehlen-8688aa207/"
  "GitHub":
    icon: "github"
    title: "GitHub"
    url: "https://github.com/christhulhu"
  "Email":
    icon: "mail"
    title: "e-mail"
    url: "mailto:christian.gehlen@gmx.net"
