
title: "Christian Gehlen"
author: "Christian Gehlen"
copyright: "2023"
description: "Product Manager and Software-Developer for Telcos"
profilePicture: "images/profile.jpg"
keywords: ""
favicon: "favicons/"
# example ["css/custom.css"]
customCss: []
# example ["js/custom.js"]
customJs: [] 
mainSections: 
  - "posts"
images: 
  - "images/site-feature-image.png"
doNotLoadAnimations: false
displayMode: "dark"
singleDateFormat: "2006-02-01"
indexDateFormat: "2006-02-01"
listDateFormat: "2006-02-01"
# Read More links for truncated summaries
# readMore: true
# postSectionName: "blog"
# relatedPosts: true
# numberOfRelatedPosts: 3

reversepagetitle: true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar: true

## Math settings
math:
  enable: false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
  use: "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
socialIcons:
  "Linkedin":
    icon: "fab fa-linkedin"
    title: "Linkedin"
    url: "https://www.linkedin.com/in/christian-gehlen-8688aa207/"
  "GitHub":
    icon: "fab fa-github"
    title: "GitHub"
    url: "https://github.com/christhulhu"
  "Email":
    icon: "fas fa-envelope"
    title: "e-mail"
    url: "mailto:chr.schmitz01@gmail.com"
