baseURL: "https://christhulhu.github.io"
languageCode: "en"
DefaultContentLanguage: "en"
title: "Christian Gehlen"

# theme as hugo module
#theme: "github.com/lxndrblz/anatole"
# theme as git submodule
#theme: "anatole"
theme: "m10c"

summarylength: 10
enableEmoji: true
enableRobotsTXT: true

# Syntax highlighting
pygmentsUseClasses: true   
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true

# Localized dates requires Hugo version 0.87.0
localizedDates: false

markup:
    goldmark:
        renderer:
          unsafe: true

taxonomies:
    category: categories
    tag: tags
