@startuml docker-compose-home-assistant
title Docker compose setup for Home Assistant
!theme blueprint

interface http

node Home-Server {

    component Traefik as ingress

    interface Webproxy as nwweb

    node home-assistant-network {
        component "Home Assistant" as hass
        component "Zigbee2mqtt" as zb
        component "mosquitto" as broker
        interface "home-assistant-network" as nwhass
    }
}

http - ingress

ingress -- nwweb

nwweb -down- hass
nwweb -down- zb

hass -- nwhass
zb -- nwhass
broker -- nwhass

hass - broker
broker - zb

@enduml