@startuml obsidian_nextcloud_git_backup
title Obsidian Notes backup sequence with Nextcloud and Git
!theme blueprint

box VPS
    participant NextCloud as nc
    participant Gitea as git
end box

box Home-Server
    participant "Home-Server" as server
    control crontab as crontab
end box

crontab --> server: ever 15 Min.\ntriggers Nextcloud sync
server <-- nc: pulls via Webdav
...
crontab --> server: at 3:00am\ntriggers Git backup
server --> server: creates local commit
server --> git: pushes changes remotely

@enduml