@startuml pihole-dns-sequence
title DNS with PiHole
!theme blueprint

actor User as user
boundary PiHole as pihole
control Traefik as traefik
participant Service as service

user -> pihole: DNS request for `service.home`
pihole -> user: IP for Docker Host
user -> traefik: request for `server.home`
activate traefik
traefik -> traefik: map request URI to Docker service
traefik -> service: request
service -> traefik: response
traefik -> user: response
deactivate traefik

@enduml